update=Fri 26 Jan 2018 03:17:15 PM EST
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=/home/rene/Git/KiCad/kicadlib/db-connectors
LibName3=/home/rene/Git/KiCad/kicadlib/db-diodes
LibName4=/home/rene/Git/KiCad/kicadlib/db-memory
LibName5=/home/rene/Git/KiCad/kicadlib/db-passives
LibName6=/home/rene/Git/KiCad/kicadlib/db-sem
LibName7=/home/rene/Git/KiCad/kicadlib/db-transistors
LibName8=/home/rene/Git/KiCad/kicadlib/db-vgparts
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=
PadDrill=0.762
PadDrillOvalY=0.762
PadSizeH=1.524
PadSizeV=1.524
PcbTextSizeV=0.889
PcbTextSizeH=0.889
PcbTextThickness=0.2032
ModuleTextSizeV=0.889
ModuleTextSizeH=0.889
ModuleTextSizeThickness=0.2032
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.1778
BoardOutlineThickness=0.254
ModuleOutlineThickness=0.15
